export const ADD_GRAPH ='ADD_GRAPH';
export const DELETE_GRAPH = 'DELETE_GRAPH';
export const SELECT_POLLUTANT = 'SELECT_POLLUTANT';
export const SELECT_STATION = 'SELECT_STATION';
export const SELECT_GRAPH = 'SELECT_GRAPH';
export const DELETE_CHOICE = 'DELETE_CHOICE';

