# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawValue',
            fields=[
                ('value_type', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='law value type')),
            ],
            options={
                'verbose_name': 'law value',
                'verbose_name_plural': 'law values',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('measured', models.DateTimeField(verbose_name='measured on')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('value', models.FloatField(null=True, verbose_name='value')),
                ('units', models.CharField(max_length=10, verbose_name='units')),
                ('status', models.IntegerField(verbose_name='status id')),
                ('is_valid', models.BooleanField(db_index=True, default=True, verbose_name='is measurement valid')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='inserted to database')),
            ],
            options={
                'verbose_name': 'measurement',
                'verbose_name_plural': 'measurements',
                'get_latest_by': 'measured',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='name')),
            ],
            options={
                'verbose_name': 'owner',
                'verbose_name_plural': 'owners',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='name')),
                ('fullname', models.CharField(max_length=60, null=True, verbose_name='verbose name')),
                ('mana_id', models.IntegerField(null=True, verbose_name='mana id')),
                ('type', models.IntegerField(verbose_name='type id')),
            ],
            options={
                'verbose_name': 'pollutant',
                'verbose_name_plural': 'pollutants',
            },
        ),
        migrations.CreateModel(
            name='PollutantLawValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='value')),
                ('units', models.CharField(max_length=35, verbose_name='units')),
                ('law_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.LawValue', verbose_name='law value type')),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.Pollutant', verbose_name='pollutant')),
            ],
            options={
                'verbose_name': 'pollutant',
                'verbose_name_plural': 'pollutants',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('region', models.CharField(max_length=35, verbose_name='region')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='monitors.Owner', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
            },
        ),
        migrations.AddField(
            model_name='pollutant',
            name='law_values',
            field=models.ManyToManyField(related_name='pollutants', through='monitors.PollutantLawValue', to='monitors.LawValue', verbose_name='pollutants law values'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitors.Pollutant', verbose_name='pollutant'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitors.Station', verbose_name='station'),
        ),
        migrations.AlterUniqueTogether(
            name='pollutantlawvalue',
            unique_together=set([('pollutant', 'law_value')]),
        ),
    ]
