# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(max_length=35, verbose_name='type')),
            ],
            options={
                'verbose_name': 'law value',
                'verbose_name_plural': 'law values',
                'ordering': ('value_type',),
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('measured', models.DateTimeField(verbose_name='measured on')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('value', models.FloatField(verbose_name='value')),
                ('units', models.CharField(max_length=35, verbose_name='units')),
                ('status', models.IntegerField(verbose_name='status id')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is measurement valid')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='queried on')),
            ],
            options={
                'verbose_name': 'measurement',
                'verbose_name_plural': 'measurements',
                'ordering': ('pollutant', 'is_valid'),
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('units', models.CharField(max_length=35, verbose_name='units of measurement')),
            ],
            options={
                'verbose_name': 'measurement',
                'verbose_name_plural': 'measurements',
                'ordering': ('station', 'pollutant', 'is_active'),
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='name')),
            ],
            options={
                'verbose_name': 'owner',
                'verbose_name_plural': 'owners',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='name')),
                ('fullname', models.CharField(max_length=60, unique=True, verbose_name='verbose name')),
                ('type', models.IntegerField(verbose_name='type id')),
                ('law_values', models.ManyToManyField(related_name='pollutants', to='monitors.LawValue', verbose_name='pollutants law values')),
            ],
            options={
                'verbose_name': 'pollutant',
                'verbose_name_plural': 'pollutants',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=35, verbose_name='name')),
                ('timebase', models.IntegerField(verbose_name='timebase')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('region', models.CharField(max_length=35, verbose_name='region')),
                ('owners', models.ManyToManyField(related_name='stations', to='monitors.Owner', verbose_name='station owners')),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
                'ordering': ('id', 'is_active'),
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='monitors.Pollutant', verbose_name='pollutant'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='monitors.Station', verbose_name='station'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitors.Monitor', verbose_name='monitor'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitors.Pollutant', verbose_name='pollutant'),
        ),
    ]
