# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='longitude'),
        ),
    ]
