# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_auto_20170502_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ('name',), 'verbose_name': 'owner', 'verbose_name_plural': 'owners'},
        ),
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
