# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_auto_20170502_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='owners',
        ),
        migrations.AddField(
            model_name='station',
            name='owners',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='monitors.Owner', verbose_name='owner'),
            preserve_default=False,
        ),
    ]
